## get all rooms
GET {{URL}}

### Get room by id.
GET {{URL}}/1

### Create room.
POST {{URL}}/
Content-Type: application/json

{
  "hotelId": 6,
  "roomNumber": 101,
  "price" : 5222.0
}

### Delete room
DELETE {{URL}}/13





